FROM python:3.12-slim

WORKDIR /game

COPY ./11.5 ./11.5
COPY ./lua ./lua
COPY Xenotactic.love .
COPY player.js .
COPY index.html .
COPY favicon.ico .
COPY coi-serviceworker.js .

EXPOSE 8000

CMD ["python", "-m", "http.server", "8000"]
