FROM python:3.12-slim

WORKDIR /game

COPY ./11.5 ./11.5
COPY ./lua ./lua
COPY Xenotactic.love .
COPY player.js .
COPY index.html .
COPY server.py .
COPY favicon.ico .

EXPOSE 8000

CMD ["python", "server.py"]
